-- 코드를 입력하세요
SELECT MEMBER_ID , MEMBER_NAME, GENDER , TO_CHAR(DATE_OF_BIRTH,'YYYY-mm-dd')
FROM MEMBER_PROFILE
WHERE GENDER='W' AND TO_CHAR(DATE_OF_BIRTH,'mm')='03' AND TLNO !='NULL'
ORDER BY MEMBER_ID ASC;